blank_issues_enabled: false
contact_links:
  - name: 📧 Email Support
    url: mailto:contato@gdzconsultoria.com.br
    about: Para suporte geral ou dúvidas
  - name: 💬 WhatsApp
    url: https://wa.me/5517991362933
    about: Para contato rápido
  - name: 📖 Documentação
    url: https://github.com/ZUKIhy/GDZConsultoria/blob/main/docs/README.md
    about: Leia a documentação completa